baseURL = "https://jiaozhong.xyz/"
languageCode = 'zh-cn'
title = '助力每一块面包的诞生'
theme = "shibui"

[markup]
  defaultMarkdownHandler = "goldmark"
  # By default, Goldmark trims unsafe outputs which might prevent some shortcodes from rendering.
  # It is recommended to set markup.goldmark.renderer.unsafe=true if you encounter problems.
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = true
    tabWidth = 4
    style = "algol_nu"
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[params]
  favicon = "/favicon.png"
  customCSS = ["css/custom.css"]
